/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    id("com.gradleup.shadow") version "9.4.1"
}

group = "dev.zenqrt"
version = "1.0-SNAPSHOT"
description = "BouncyBullets"

val lampVersion: String by project

repositories {
    mavenCentral()
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
}

dependencies {
    paperweight.paperDevBundle("26.1.2.build.+")

    implementation("io.github.revxrsal:lamp.common:${lampVersion}")
    implementation("io.github.revxrsal:lamp.bukkit:${lampVersion}")
    implementation("io.github.revxrsal:lamp.brigadier:${lampVersion}")

    implementation("com.github.stefvanschie.inventoryframework:IF:0.12.0")

    implementation(platform("org.mongodb:mongodb-driver-bom:5.7.0"))
    implementation("org.mongodb:mongodb-driver-sync")

    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

paperweight {
    javaLauncher = javaToolchains.launcherFor {
        // Example scenario:
        // Paper 1.17.1 was originally built with JDK 16 and the bundle
        // has not been updated to work with 21+ (but we want to compile with a 25 toolchain)
        languageVersion = JavaLanguageVersion.of(25)
    }
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

tasks.jar {
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

tasks.shadowJar {
    archiveFileName.set("BouncyBullets.jar")
    destinationDirectory.set(file(".\\server\\plugins"))
    relocate("com.github.stefvanschie.inventoryframework", "dev.zenqrt.bouncybullets.inventoryframework")
}

tasks.test {
    useJUnitPlatform()
}