#########################
# Database Configuration
#########################

#### MongoDB (uncomment to enable)
#mongodb:
#  connection_string: "replace me"
#  database: "bouncy_bullets"
#  stats_collection: "player_stats"